#include "model.hpp"

namespace model
{
namespace enums
{
	void init_converter_impl()
	{
		#define BEGIN_FOR(struct_name) { using t = struct_name;
		#define NAME2TYPE_ELEMENT(name) add_definition(t::name, #name);
		#define END_FOR() }

		BEGIN_FOR(Type)
			NAME2TYPE_ELEMENT(Alcohol)
			NAME2TYPE_ELEMENT(Arms)
			NAME2TYPE_ELEMENT(ArtAnalyzer)
			NAME2TYPE_ELEMENT(ArtAntigrav)
			NAME2TYPE_ELEMENT(ArtDecelerate)
			NAME2TYPE_ELEMENT(ArtDefToArms1)
			NAME2TYPE_ELEMENT(ArtDefToArms2)
			NAME2TYPE_ELEMENT(ArtDefToEnergy)
			NAME2TYPE_ELEMENT(ArtDroid)
			NAME2TYPE_ELEMENT(ArtEnergyDef)
			NAME2TYPE_ELEMENT(ArtForsage)
			NAME2TYPE_ELEMENT(ArtFuel)
			NAME2TYPE_ELEMENT(ArtGiperJump)
			NAME2TYPE_ELEMENT(ArtHook)
			NAME2TYPE_ELEMENT(ArtHull)
			NAME2TYPE_ELEMENT(ArtMiniExpl)
			NAME2TYPE_ELEMENT(ArtNano)
			NAME2TYPE_ELEMENT(ArtPDTurret)
			NAME2TYPE_ELEMENT(ArtPower)
			NAME2TYPE_ELEMENT(ArtRadar)
			NAME2TYPE_ELEMENT(ArtScaner)
			NAME2TYPE_ELEMENT(ArtSpeed)
			NAME2TYPE_ELEMENT(ArtSplinter)
			NAME2TYPE_ELEMENT(ArtTransmitter)
			NAME2TYPE_ELEMENT(ArtWeaponToSpeed)
			NAME2TYPE_ELEMENT(BK)
			NAME2TYPE_ELEMENT(CB)
			NAME2TYPE_ELEMENT(CargoHook)
			NAME2TYPE_ELEMENT(Cistern)
			NAME2TYPE_ELEMENT(DefGenerator)
			NAME2TYPE_ELEMENT(Engine)
			NAME2TYPE_ELEMENT(Food)
			NAME2TYPE_ELEMENT(FuelTanks)
			NAME2TYPE_ELEMENT(Hull)
			NAME2TYPE_ELEMENT(Kling)
			NAME2TYPE_ELEMENT(Luxury)
			NAME2TYPE_ELEMENT(MC)
			NAME2TYPE_ELEMENT(Medicine)
			NAME2TYPE_ELEMENT(Minerals)
			NAME2TYPE_ELEMENT(Narcotics)
			NAME2TYPE_ELEMENT(Nod)
			NAME2TYPE_ELEMENT(PB)
			NAME2TYPE_ELEMENT(Pirate)
			NAME2TYPE_ELEMENT(Protoplasm)
			NAME2TYPE_ELEMENT(RC)
			NAME2TYPE_ELEMENT(Radar)
			NAME2TYPE_ELEMENT(Ranger)
			NAME2TYPE_ELEMENT(RepairRobot)
			NAME2TYPE_ELEMENT(Satellite)
			NAME2TYPE_ELEMENT(SB)
			NAME2TYPE_ELEMENT(Scaner)
			NAME2TYPE_ELEMENT(Technics)
			NAME2TYPE_ELEMENT(Transport)
			NAME2TYPE_ELEMENT(UselessItem)
			NAME2TYPE_ELEMENT(W01)
			NAME2TYPE_ELEMENT(W02)
			NAME2TYPE_ELEMENT(W03)
			NAME2TYPE_ELEMENT(W04)
			NAME2TYPE_ELEMENT(W05)
			NAME2TYPE_ELEMENT(W06)
			NAME2TYPE_ELEMENT(W07)
			NAME2TYPE_ELEMENT(W08)
			NAME2TYPE_ELEMENT(W09)
			NAME2TYPE_ELEMENT(W10)
			NAME2TYPE_ELEMENT(W11)
			NAME2TYPE_ELEMENT(W12)
			NAME2TYPE_ELEMENT(W13)
			NAME2TYPE_ELEMENT(W14)
			NAME2TYPE_ELEMENT(W15)
			NAME2TYPE_ELEMENT(W16)
			NAME2TYPE_ELEMENT(W17)
			NAME2TYPE_ELEMENT(W18)
			NAME2TYPE_ELEMENT(W19)
			NAME2TYPE_ELEMENT(W20)
			NAME2TYPE_ELEMENT(W21)
			NAME2TYPE_ELEMENT(W22)
			NAME2TYPE_ELEMENT(W23)

			NAME2TYPE_ELEMENT(WB)
			NAME2TYPE_ELEMENT(Warrior)
		END_FOR()

		BEGIN_FOR(GoodsEnum)
			NAME2TYPE_ELEMENT(Food)
			NAME2TYPE_ELEMENT(Medicine)
			NAME2TYPE_ELEMENT(Alcohol)
			NAME2TYPE_ELEMENT(Minerals)
			NAME2TYPE_ELEMENT(Luxury)
			NAME2TYPE_ELEMENT(Technics)
			NAME2TYPE_ELEMENT(Arms)
			NAME2TYPE_ELEMENT(Narcotics)
		END_FOR()
		
		BEGIN_FOR(OwnersGroup)
			NAME2TYPE_ELEMENT(Klings)
			NAME2TYPE_ELEMENT(Normals)
			NAME2TYPE_ELEMENT(Pirates)
		END_FOR()

		BEGIN_FOR(Owner)
			NAME2TYPE_ELEMENT(None)
			NAME2TYPE_ELEMENT(Kling)
			NAME2TYPE_ELEMENT(Fei)
			NAME2TYPE_ELEMENT(Gaal)
			NAME2TYPE_ELEMENT(Maloc)
			NAME2TYPE_ELEMENT(Peleng)
			NAME2TYPE_ELEMENT(People)
			NAME2TYPE_ELEMENT(PirateClan)
		END_FOR()

		BEGIN_FOR(Goverment)
			NAME2TYPE_ELEMENT(Anarchy)
			NAME2TYPE_ELEMENT(Democracy)
			NAME2TYPE_ELEMENT(Dictatorship)
			NAME2TYPE_ELEMENT(Monarchy)
			NAME2TYPE_ELEMENT(Republic)
		END_FOR()

		#undef BEGIN_FOR
		#undef NAME2TYPE_ELEMENT
		#undef END_FOR
	}

} // namespace enums


struct staticIniter
{
	staticIniter()
	{
		//kv::init_storage_impl();
		enums::init_converter_impl();
	}
};

static staticIniter initer;
}